//fetch
export const FETCH_DATA_INIT = "FETCH_DATA_INIT";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const FORM_USER_CONTACTS = "FORM_USER_CONTACTS";

//Post
export const POST_DATA_INIT = "POST_DATA_INIT";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILURE = "POST_DATA_FAILURE";
