export const FETCH_DATA_INIT = "FETCH_DATA_INIT";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const FORM_USER_CONTACTS = "FORM_USER_CONTACTS";

/*export const FETCH_DATA_INIT = "FETCH_DATA_INIT";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE"; */
